import { TerminalPreferences, Theme } from '../types'

export const builtInThemes: Theme[] = [
  {
    id: 'sorbet',
    name: 'Sorbet',
    background: '#11161d',
    foreground: '#edf6ff',
    cursor: '#7ef9ff',
    cursorAccent: '#11161d',
    selectionBackground: '#7ef9ff33',
    black: '#202735',
    red: '#ff5fa2',
    green: '#b9ff6f',
    yellow: '#ffe66b',
    blue: '#7da6ff',
    magenta: '#d98cff',
    cyan: '#7ef9ff',
    white: '#edf6ff',
    brightBlack: '#526175',
    brightRed: '#ff8cbc',
    brightGreen: '#d2ff9a',
    brightYellow: '#fff19a',
    brightBlue: '#a6c1ff',
    brightMagenta: '#ebb2ff',
    brightCyan: '#b8fdff',
    brightWhite: '#ffffff',
    accent: '#ff5fa2',
  },
  {
    id: 'dark',
    name: 'Midnight Graphite',
    background: '#0d0d0f',
    foreground: '#e4e4e7',
    cursor: '#22d3ee',
    cursorAccent: '#0d0d0f',
    selectionBackground: '#22d3ee33',
    black: '#18181b',
    red: '#f87171',
    green: '#4ade80',
    yellow: '#fbbf24',
    blue: '#60a5fa',
    magenta: '#c084fc',
    cyan: '#22d3ee',
    white: '#e4e4e7',
    brightBlack: '#3f3f46',
    brightRed: '#fca5a5',
    brightGreen: '#86efac',
    brightYellow: '#fde68a',
    brightBlue: '#93c5fd',
    brightMagenta: '#d8b4fe',
    brightCyan: '#67e8f9',
    brightWhite: '#f4f4f5',
    accent: '#22d3ee',
  },
  {
    id: 'dracula',
    name: 'Dracula',
    background: '#282a36',
    foreground: '#f8f8f2',
    cursor: '#bd93f9',
    cursorAccent: '#282a36',
    selectionBackground: '#44475a',
    black: '#21222c',
    red: '#ff5555',
    green: '#50fa7b',
    yellow: '#f1fa8c',
    blue: '#6272a4',
    magenta: '#bd93f9',
    cyan: '#8be9fd',
    white: '#f8f8f2',
    brightBlack: '#6272a4',
    brightRed: '#ff6e6e',
    brightGreen: '#69ff94',
    brightYellow: '#ffffa5',
    brightBlue: '#d6acff',
    brightMagenta: '#ff92df',
    brightCyan: '#a4ffff',
    brightWhite: '#ffffff',
    accent: '#bd93f9',
  },
  {
    id: 'nord',
    name: 'Nord',
    background: '#2e3440',
    foreground: '#d8dee9',
    cursor: '#88c0d0',
    cursorAccent: '#2e3440',
    selectionBackground: '#4c566a',
    black: '#3b4252',
    red: '#bf616a',
    green: '#a3be8c',
    yellow: '#ebcb8b',
    blue: '#81a1c1',
    magenta: '#b48ead',
    cyan: '#88c0d0',
    white: '#e5e9f0',
    brightBlack: '#4c566a',
    brightRed: '#bf616a',
    brightGreen: '#a3be8c',
    brightYellow: '#ebcb8b',
    brightBlue: '#81a1c1',
    brightMagenta: '#b48ead',
    brightCyan: '#8fbcbb',
    brightWhite: '#eceff4',
    accent: '#88c0d0',
  },
  {
    id: 'tokyonight',
    name: 'Tokyo Night',
    background: '#1a1b26',
    foreground: '#a9b1d6',
    cursor: '#7aa2f7',
    cursorAccent: '#1a1b26',
    selectionBackground: '#283457',
    black: '#15161e',
    red: '#f7768e',
    green: '#9ece6a',
    yellow: '#e0af68',
    blue: '#7aa2f7',
    magenta: '#bb9af7',
    cyan: '#7dcfff',
    white: '#a9b1d6',
    brightBlack: '#414868',
    brightRed: '#f7768e',
    brightGreen: '#9ece6a',
    brightYellow: '#e0af68',
    brightBlue: '#7aa2f7',
    brightMagenta: '#bb9af7',
    brightCyan: '#7dcfff',
    brightWhite: '#c0caf5',
    accent: '#7aa2f7',
  },
  {
    id: 'catppuccin',
    name: 'Catppuccin Mocha',
    background: '#1e1e2e',
    foreground: '#cdd6f4',
    cursor: '#f5c2e7',
    cursorAccent: '#1e1e2e',
    selectionBackground: '#45475a',
    black: '#45475a',
    red: '#f38ba8',
    green: '#a6e3a1',
    yellow: '#f9e2af',
    blue: '#89b4fa',
    magenta: '#f5c2e7',
    cyan: '#94e2d5',
    white: '#bac2de',
    brightBlack: '#585b70',
    brightRed: '#f38ba8',
    brightGreen: '#a6e3a1',
    brightYellow: '#f9e2af',
    brightBlue: '#89b4fa',
    brightMagenta: '#f5c2e7',
    brightCyan: '#94e2d5',
    brightWhite: '#a6adc8',
    accent: '#cba6f7',
  },
  {
    id: 'gruvbox',
    name: 'Gruvbox Dark',
    background: '#282828',
    foreground: '#ebdbb2',
    cursor: '#fe8019',
    cursorAccent: '#282828',
    selectionBackground: '#3c3836',
    black: '#282828',
    red: '#cc241d',
    green: '#98971a',
    yellow: '#d79921',
    blue: '#458588',
    magenta: '#b16286',
    cyan: '#689d6a',
    white: '#a89984',
    brightBlack: '#928374',
    brightRed: '#fb4934',
    brightGreen: '#b8bb26',
    brightYellow: '#fabd2f',
    brightBlue: '#83a598',
    brightMagenta: '#d3869b',
    brightCyan: '#8ec07c',
    brightWhite: '#ebdbb2',
    accent: '#fe8019',
  },
]

export const builtInThemesById: Record<string, Theme> = Object.fromEntries(
  builtInThemes.map((theme) => [theme.id, theme])
)

export const defaultTheme = builtInThemes[0]

export const defaultTerminalPreferences: TerminalPreferences = {
  defaultThemeId: defaultTheme.id,
  fontFamily: '"JetBrains Mono", "Fira Code", "Cascadia Code", Menlo, monospace',
  fontSize: 13,
  lineHeight: 1.2,
  letterSpacing: 0,
  scrollback: 5000,
  enableClipboardShortcuts: true,
  rightClickPaste: false,
  middleClickPaste: true,
  copyShortcut: 'CmdOrCtrl+Shift+C',
  pasteShortcut: 'CmdOrCtrl+Shift+V',
}

export function mergeThemes(customThemes: Theme[]): Theme[] {
  const seen = new Set<string>(builtInThemes.map((theme) => theme.id))
  const uniqueCustomThemes = customThemes.filter((theme) => {
    if (seen.has(theme.id)) return false
    seen.add(theme.id)
    return true
  })

  return [...builtInThemes, ...uniqueCustomThemes]
}
